<?php
require __DIR__ . '/app/core.php';
$token=(string)($_GET['token']??'');
$authorization=null;$error=null;
if($token!==''){try{$authorization=validate_exit_token($token,false);}catch(Throwable $e){$error=$e->getMessage();}}
$hotel=htmlspecialchars((string)setting('hotel_name',cfg('hotel_name')),ENT_QUOTES,'UTF-8');
$logo=htmlspecialchars(branding_url('logo_filename') ?: app_url('assets/logo.php'),ENT_QUOTES,'UTF-8');
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Portaria · <?= $hotel ?></title><link rel="stylesheet" href="<?= htmlspecialchars(app_url('assets/app.css')) ?>?v=3"></head><body>
<header class="topbar"><div class="brand"><img src="<?= $logo ?>" alt="<?= $hotel ?>"><div><strong>Validação de saída</strong><small>Portaria</small></div></div><a class="btn btn-secondary" href="<?= htmlspecialchars(app_url('index.php')) ?>">Totem</a></header><main class="kiosk-main" style="max-width:780px">
<section class="panel"><h1 class="step-title" style="font-size:2.4rem">Autorização de saída</h1><p class="step-subtitle">Abra esta página pelo QR Code emitido no check-out ou cole o token abaixo.</p><form method="get" class="section-card"><label class="form-label">Token</label><textarea name="token" class="form-control" rows="3"><?= htmlspecialchars($token) ?></textarea><button class="btn btn-primary" style="margin-top:12px">Validar</button></form>
<?php if($error): ?><div class="alert alert-danger"><strong>Saída não autorizada.</strong><br><?= htmlspecialchars($error) ?></div><?php elseif($authorization): ?><div id="authorization" class="alert alert-success"><strong>Autorização válida.</strong></div><div class="summary-grid"><div class="summary-box"><small>Reserva</small><strong><?= htmlspecialchars($authorization['reservation_number']) ?></strong></div><div class="summary-box"><small>UH</small><strong><?= htmlspecialchars($authorization['room_number']??'—') ?></strong></div><div class="summary-box"><small>Responsável</small><strong><?= htmlspecialchars($authorization['responsible_name']) ?></strong></div></div><div class="section-card"><p>Comprovante: <strong><?= htmlspecialchars($authorization['receipt_number']) ?></strong></p><p>Válido até: <strong><?= htmlspecialchars($authorization['expires_at']) ?></strong></p><button id="consume" class="btn btn-primary btn-lg">Confirmar saída do hóspede</button></div><?php endif; ?>
</section></main><div id="toast" class="toast hidden"></div><script>window.TOTEM_BASE=<?= json_encode(app_base_path(),JSON_UNESCAPED_SLASHES) ?>;window.EXIT_TOKEN=<?= json_encode($token) ?>;</script><script><?php if($authorization): ?>document.getElementById('consume').onclick=async()=>{const b=document.getElementById('consume');try{b.disabled=true;b.textContent='Confirmando...';const r=await fetch(`${window.TOTEM_BASE}/api.php?action=exit_consume`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:window.EXIT_TOKEN})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Falha');document.getElementById('authorization').innerHTML='<strong>Saída confirmada.</strong> Autorização consumida com sucesso.';b.remove()}catch(e){alert(e.message);b.disabled=false;b.textContent='Confirmar saída do hóspede'}};<?php endif; ?></script></body></html>
