<?php
require __DIR__ . '/app/core.php';
$hotel=htmlspecialchars((string)setting('hotel_name',cfg('hotel_name')),ENT_QUOTES,'UTF-8');
$logo=htmlspecialchars(branding_url('logo_filename') ?: app_url('assets/logo.php'),ENT_QUOTES,'UTF-8');
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reservas · <?= $hotel ?></title><link rel="stylesheet" href="<?= htmlspecialchars(app_url('assets/app.css')) ?>?v=3"></head><body>
<header class="topbar"><div class="brand"><img src="<?= $logo ?>" alt="<?= $hotel ?>"><div><strong>Gestão de reservas</strong><small>V3 PHP</small></div></div><div class="admin-links"><a class="btn btn-secondary" href="<?= htmlspecialchars(app_url('index.php')) ?>">Totem</a><button class="btn btn-danger" id="logout">Sair</button></div></header>
<main class="kiosk-main" style="width:min(1540px,calc(100% - 32px))">
<section id="loginBox" class="panel" style="max-width:460px;margin:50px auto"><h1 class="step-title" style="font-size:2rem">Gestão de reservas</h1><p class="step-subtitle">Informe a senha administrativa.</p><label class="form-label">Senha</label><input id="password" type="password" inputmode="numeric" class="form-control"><button id="login" class="btn btn-primary btn-lg" style="width:100%;margin-top:14px">Entrar</button><div id="loginError" class="alert alert-danger hidden"></div></section>
<section id="dashboard" class="hidden"><div class="flow-actions" style="margin-top:0"><div><div class="step-badge">PAINEL OPERACIONAL</div><h1 class="step-title">Reservas</h1><p class="step-subtitle">Reservas integradas, manuais e demonstrações.</p></div><button id="newReservation" class="btn btn-primary btn-lg">＋ Nova reserva manual</button></div><div id="stats" class="summary-grid"></div><div class="panel" style="padding:18px;margin-bottom:18px"><div class="row"><div class="col-6"><label class="form-label">Buscar</label><input id="search" class="form-control" placeholder="Reserva, responsável, CPF, UH ou ID externo"></div><div class="col-3"><label class="form-label">Status</label><select id="status" class="form-select"><option value="">Todos</option><option value="reserved">Aguardando check-in</option><option value="checked_in">Hospedado</option><option value="checked_out">Check-out concluído</option><option value="cancelled">Cancelada</option></select></div><div class="col-3"><label class="form-label">Origem</label><select id="source" class="form-select"><option value="">Todas</option><option value="manual">Manual</option><option value="integration">Integração</option><option value="demo">Demonstração</option></select></div></div></div><div class="panel" style="padding:0;overflow:auto"><table style="width:100%;border-collapse:collapse;min-width:1100px"><thead><tr style="background:#f5faf7"><th style="padding:14px;text-align:left">Reserva</th><th style="padding:14px;text-align:left">Responsável</th><th>Período</th><th>UH</th><th>Hóspedes</th><th>Processo</th><th>Saldo</th><th>Status</th><th></th></tr></thead><tbody id="rows"></tbody></table><div id="empty" class="hidden" style="padding:50px;text-align:center;color:var(--muted)">Nenhuma reserva encontrada.</div></div></section>
</main><div id="modalRoot"></div><div id="toast" class="toast hidden"></div><script>window.TOTEM_BASE=<?= json_encode(app_base_path(),JSON_UNESCAPED_SLASHES) ?>;</script><script src="<?= htmlspecialchars(app_url('assets/reservas.js')) ?>?v=3"></script></body></html>
